name: Проверка всех .py файлов

on:
  push:
    branches: [proga]
  pull_request:
    branches: [proga]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Клонируем репозиторий
        uses: actions/checkout@v3

      - name: Устанавливаем Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Устанавливаем зависимости (если есть requirements.txt)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Запускаем все .py файлы
        run: |
          for file in /*.py; do
            echo "Запуск $file"
            python "$file"
          done
          
