name: Запуск всех .py файлов из лабораторных

on:
  push:
    branches: [proga]
  pull_request:
    branches: [proga]

jobs:
  run-python-files:
    runs-on: ubuntu-latest

    steps:
      - name: Клонируем репозиторий
        uses: actions/checkout@v3

      - name: Устанавливаем Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Устанавливаем зависимости
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Запускаем все .py файлы, кроме с "kekw"
        run: |
          echo "Запуск всех .py файлов..."
          find . -type f -name "*.py" | while read file; do
            echo ">>> python $file"
            python "$file"
          done
